hdu:
  datasource:
    host: localhost
    port: 3306
    database: cloud_desktop
    username: root
    password: 522436
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 522436

